### ISSUE TITLE
Proposal: All external links should open in a new tab

### ISSUE THREAD

**Issue by KrauseFx** [danger/danger.systems#52]
Links to external sites like RubyGems.org should open in a new window using `target="_blank"`. This should be default for all auto-generated HTML sites

**Comment by orta** [comment]
Yep, good call

**Comment by orta** [comment]
Can be done as a middleman hook and nokogiri - similar to how we add links to markdown headers

**Comment by hanneskaeufler** [comment]
This was fixed in #79
