### ISSUE TITLE
In-page links don't exist

### ISSUE THREAD

**Issue by dblock** [danger/danger.systems#54]
eg. https://github.com/danger/danger.systems/blob/master/static/source/guides/getting_started.html.slim#L16

So http://danger.systems/guides/getting_started.html#creating-a-github-account-for-danger-to-use doesn't go anywhere.

Played around with this, but didn't find the "official" way of fixing it.

**Comment by orta** [comment]
Yeah, I spotted this when making your guides - wanted to do some artsy work before getting back to it, but yeah, not too sure on the answer yet
