### ISSUE TITLE
GitHub account: write access, right?

### ISSUE THREAD

**Issue by epologee** [danger/danger.systems#56]
https://github.com/danger/danger.systems/blob/master/static/source/guides/getting_started.html.slim#L73 states you should add the bot to the (closed source) repo. Doing that GitHub will present options for `Admin`, `Write` or `Read`. I'm assuming the bot needs write-access, but it might prevent some confusion if this were part of the getting started docs.

Happy to submit a pull request if this is correct and you agree. Cheers!

**Comment by orta** [comment]
I _think_ it only needs read - though I have no private repos to test it on :D

**Comment by orta** [comment]
The Danger bot only needs to comment on PRs, I think that would be allowable via read

**Comment by epologee** [comment]
When I change the access to 'Read', Danger fails quite neatly with:

> Danger has failed this build. 
Found 1 error and I don't have write access to the PR set a PR status.

So I guess write access is required!

**Comment by orta** [comment]
Yep - makes sense then 👍

**Comment by epologee** [comment]
Alright, I've created PR #60 for it, let's close this one.
