### ISSUE TITLE
Double-click for selecting is tricky

### ISSUE THREAD

**Issue by ashfurrow** [danger/danger.systems#59]
In the reference page at http://danger.systems/reference.html if you double-click one of the method names (like `insertions` for example), you'll get a kind of weird text selection:

![screen shot 2016-07-27 at 1 14 18 pm](https://cloud.githubusercontent.com/assets/498212/17184825/40b95762-53fc-11e6-8a10-4865a37b0f8e.png)

See the purple line indicating more is selected? It's not a big deal except if I copy what is selected, I've actually copied "insertionsFixnum" – not a huge deal, I'll see if I can fix it sometime.

**Comment by ashfurrow** [comment]
Sorry, hit enter in the title field, I'll add an issue body.

**Comment by orta** [comment]
probably needs to change the `span` to be a `div` for the `-> XXX`
