### ISSUE TITLE
Moya example Dangerfile incorrect syntax

### ISSUE THREAD

**Issue by bentrengrove** [danger/danger.systems#78]
The Moya example Dangerfile uses lines_of_code instead of git.lines_of_code.

Might be others, just noticed as I was going through.

**Comment by marcelofabri** [comment]
Those examples are extracted directly from the respective repos: https://github.com/danger/danger.systems/blob/master/Rakefile#L42

I've opened a PR on Moya to fix the one the you've reported: https://github.com/Moya/Moya/pull/577

**Comment by orta** [comment]
Thanks all, this will get fixed next time we merge a PR on this repo now 👍
